language: elixir
elixir:
  - 1.3.2
otp_release:
  - 18.2
addons:
  postgresql: "9.5"
  apt:
    packages:
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6
sudo: required
dist: trusty # only environment that supports Postgres 9.5 at this time
env:
  - ELIXIR_ERL_OPTIONS=""
  - ELIXIR_ERL_OPTIONS="+T 9"
install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - (cd examples/friends; mix deps.get)
script:
  - mix test
  - ECTO_POOL=poolboy mix test.adapters
  - ECTO_POOL=sbroker mix test.adapters
  - (cd examples/friends; mix test)
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
notifications:
  recipients:
    - jose.valim@plataformatec.com.br
    - eric.meadows.jonsson@gmail.com
